/* Q4.27  Fibonacci Sequence

The Fibonacci sequence is the series of numbers 
0, 1, 1, 2, 3, 5, 8, …. 
Formally, it can be expressed as: 
fib 0 = 0 
fib 1 = 1 
fib n = fib n − 1 + fib n − 2 
Write a multithreaded program that generates the Fibonacci sequence. 
This program should work as follows: On the command line, the user 
will enter the number of Fibonacci numbers that the program is to 
generate. The program will then create a separate thread that will 
generate the Fibonacci numbers, placing the sequence in data that 
can be shared by the threads (an array is probably the most convenient 
data structure). When the thread finishes execution, the parent 
thread will output the sequence generated by the child thread. 
Because the parent thread cannot begin outputting the Fibonacci 
sequence until the child thread finishes, the parent thread will 
have to wait for the child thread to finish. Use the techniques 
described in Section 4.4 to meet this requirement.
 */
/**
 * Pthreads solution to exercise 4.27
 *
 * Operating System Concepts  - Tenth Edition
 * Copyright John Wiley & Sons - 2018.
 */

#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>

/** we will only allow up to 256 fibonacci numbers */
#define MAX_SIZE 256

int fibs[MAX_SIZE];

void *runner(void *param); /* the thread */

int main(int argc, char *argv[])
{
int i;
pthread_t tid; /* the thread identifier */
pthread_attr_t attr; /* set of attributes for the thread */

if (argc != 2) {
	fprintf(stderr,"usage: a.out <integer value>\n");
	return -1;
}

if (atoi(argv[1]) < 0) {
	fprintf(stderr,"Argument %d must be >= 0 \n",atoi(argv[1]));
	return -1;
}

/* get the default attributes */
pthread_attr_init(&attr);

/* create the thread */
pthread_create(&tid,&attr,runner,argv[1]);

/* now wait for the thread to exit */
pthread_join(tid,NULL);

/** now output the Fibonacci numbers */
for (i = 0; i < atoi(argv[1]); i++)
	printf("%d\n", fibs[i]);
}

/**
 * Generate primes using the Sieve of Eratosthenes.
 */
void *runner(void *param) 
{
int i;
int upper = atoi(param);

	if (upper== 0)
		pthread_exit(0);
	else if (upper == 1)
		fibs[0] = 0;
	else if (upper== 2) {
		fibs[0] = 0;
		fibs[1] = 1;
	}
	else { // sequence > 2
		fibs[0] = 0;
		fibs[1] = 1;

		for (i = 2; i < upper; i++)
			fibs[i] = fibs[i-1] + fibs[i-2];
	}
		
	pthread_exit(0);
}
